import{a as d,i as u,S as h}from"./assets/vendor-1dbc2c2a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const f={hidden:"visually-hidden"},l=e=>{e.classList.remove(f.hidden)},a=e=>{e.classList.add(f.hidden)},y=e=>Array.isArray(e)&&e.length>0,m=(e,o,s)=>{if(y(e)){a(o.loader),s(e);return}throw new Error("All cats are busy sipping milk, sorry. Try again later")},p={fetchAll:"/breeds",fetchByBreedId:"/images/search"};d.defaults.headers.common["x-api-key"]="live_8TsNZUhy5iYCK9WChJmZgi01iIAI2KzPJncbfC1OOay2wDsfjyjytcNtUNPWpqPi";d.defaults.baseURL="https://api.thecatapi.com/v1";const g=()=>d.get(p.fetchAll),b=e=>{const o=new URLSearchParams({breed_ids:e});return d.get(`${p.fetchByBreedId}?${o}`)},r={breedSelect:document.querySelector("select.breed-select"),loader:document.querySelector("span.loader"),infoBlock:document.querySelector("div.cat-info")},S=e=>{const o=e.map((s,c)=>c===0?"<option value disabled selected>Select a breed</option>":`<option value="${s.id}">${s.name}</option>`).join("");r.breedSelect.insertAdjacentHTML("beforeend",o),new h({select:"select.breed-select"})},v=e=>{const{url:o,breeds:s}=e[0],{name:c,description:t,temperament:n}=s[0],i=`
  <img src=${o} width="400" alt="${c||"cat"}"/>
  <div class="text-wrap">
    <h1 class="main-title">${c}</h1>
    <p>${t}</p>
    <p><strong>Temperament:</strong> ${n}</p>
  </div>
      `;r.infoBlock.innerHTML=i},L=()=>{const e=r.breedSelect.selectedIndex,o=r.breedSelect.options[e].value;a(r.infoBlock),l(r.loader),b(o).then(({data:s})=>{m(s,r,v),l(r.infoBlock)}).catch(s=>{console.error("error:",s),a(r.loader),u.error({message:`${s.message}`,position:"topCenter"})})};r&&l(r.loader);g().then(({data:e})=>{m(e,r,S),l(r.breedSelect)}).catch(e=>{console.log("error:",e),a(r.loader),u.error({message:`${e.message}`,position:"topCenter"})});r.breedSelect.addEventListener("change",L);
//# sourceMappingURL=commonHelpers.js.map
