import{a}from"./assets/vendor-a2e8d7fa.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const u={hidden:"visually-hidden"},i=e=>{e.classList.remove(u.hidden)},d=e=>{e.classList.add(u.hidden)},p=e=>Array.isArray(e)&&e.length>0,f=(e,o,s)=>{if(p(e)){d(o.loader),s(e);return}throw o.error.textContent="All cats are busy sipping milk, sorry. Try again later",new Error("No data for this query")},h={fetchAll:"/breeds",fetchByBreedId:"/images/search"};a.defaults.headers.common["x-api-key"]="live_8TsNZUhy5iYCK9WChJmZgi01iIAI2KzPJncbfC1OOay2wDsfjyjytcNtUNPWpqPi";a.defaults.baseURL="https://api.thecatapi.com/v1";const m=()=>a.get(h.fetchAll),y=e=>{const o=new URLSearchParams({breed_ids:e});return a.get(`${h.fetchByBreedId}?${o}`)},t={breedSelect:document.querySelector("select.breed-select"),loader:document.querySelector("p.loader"),error:document.querySelector("p.error"),infoBlock:document.querySelector("div.cat-info")},g=e=>{const o=e.map((s,c)=>c===0?"<option value disabled selected>Select a breed</option>":`<option value="${s.id}">${s.name}</option>`).join("");t.breedSelect.insertAdjacentHTML("beforeend",o)},b=e=>{const{url:o,breeds:s}=e[0],{name:c,description:r,temperament:n}=s[0],l=`
  <img src=${o} width="400" alt="${c||"cat"}"/>
  <div class="text-wrap">
    <h1 class="main-title">${c}</h1>
    <p>${r}</p>
    <p><strong>Temperament:</strong> ${n}</p>
  </div>
      `;t.infoBlock.innerHTML=l},S=()=>{const e=t.breedSelect.selectedIndex,o=t.breedSelect.options[e].value;d(t.error),d(t.infoBlock),i(t.loader),y(o).then(({data:s})=>{f(s,t,b),i(t.infoBlock)}).catch(s=>{console.error("error:",s),d(t.loader),i(t.error)})};t&&i(t.loader);m().then(({data:e})=>{f(e,t,g),i(t.breedSelect)}).catch(e=>{console.log("error:",e),d(t.loader),i(t.error)});t.breedSelect.addEventListener("change",S);
//# sourceMappingURL=commonHelpers.js.map
