import{a as d,i as u}from"./assets/vendor-60fbd1ed.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const f={hidden:"visually-hidden"},l=e=>{e.classList.remove(f.hidden)},a=e=>{e.classList.add(f.hidden)},h=e=>Array.isArray(e)&&e.length>0,p=(e,o,n)=>{if(h(e)){a(o.loader),n(e);return}throw new Error("All cats are busy sipping milk, sorry. Try again later")},m={fetchAll:"/breeds",fetchByBreedId:"/images/search"};d.defaults.headers.common["x-api-key"]="live_8TsNZUhy5iYCK9WChJmZgi01iIAI2KzPJncbfC1OOay2wDsfjyjytcNtUNPWpqPi";d.defaults.baseURL="https://api.thecatapi.com/v1";const y=()=>d.get(m.fetchAll),g=e=>{const o=new URLSearchParams({breed_ids:e});return d.get(`${m.fetchByBreedId}?${o}`)},r={breedSelect:document.querySelector("select.breed-select"),loader:document.querySelector("span.loader"),infoBlock:document.querySelector("div.cat-info")},b=e=>{const o=e.map((n,c)=>c===0?"<option value disabled selected>Select a breed</option>":`<option value="${n.id}">${n.name}</option>`).join("");r.breedSelect.insertAdjacentHTML("beforeend",o)},S=e=>{const{url:o,breeds:n}=e[0],{name:c,description:t,temperament:s}=n[0],i=`
  <img src=${o} width="400" alt="${c||"cat"}"/>
  <div class="text-wrap">
    <h1 class="main-title">${c}</h1>
    <p>${t}</p>
    <p><strong>Temperament:</strong> ${s}</p>
  </div>
      `;r.infoBlock.innerHTML=i},v=()=>{const e=r.breedSelect.selectedIndex,o=r.breedSelect.options[e].value;a(r.infoBlock),l(r.loader),g(o).then(({data:n})=>{p(n,r,S),l(r.infoBlock)}).catch(n=>{console.error("error:",n),a(r.loader),u.error({message:`${n.message}`,position:"topCenter"})})};r&&l(r.loader);y().then(({data:e})=>{p(e,r,b),l(r.breedSelect)}).catch(e=>{console.log("error:",e),a(r.loader),u.error({message:`${e.message}`,position:"topCenter"})});r.breedSelect.addEventListener("change",v);
//# sourceMappingURL=commonHelpers.js.map
